# Generated by Django 6.0.5 on 2026-05-21 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=450)),
                ('emp_sal', models.FloatField()),
                ('emp_add', models.CharField(max_length=950)),
            ],
        ),
    ]
